# Generated by Django 3.0.7 on 2021-11-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarNumberApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnumber',
            name='car_number',
            field=models.CharField(max_length=36, null=True, verbose_name='Car Number'),
        ),
    ]
