# Generated by Django 3.0.7 on 2021-11-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarNumberApp', '0002_carnumber_car_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnumber',
            name='en_dis',
            field=models.BooleanField(default=True, verbose_name='Enable/Disable'),
        ),
    ]
