# Generated by Django 3.0.7 on 2021-11-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarNumberApp', '0004_carnumberapartmentowner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carnumberapartmentowner',
            unique_together={('car_number_id',)},
        ),
    ]
