# Generated by Django 3.0.7 on 2021-11-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarNumberApp', '0005_auto_20211114_1042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carnumberapartmentowner',
            unique_together=set(),
        ),
    ]
