# Generated by Django 3.0.7 on 2021-11-14 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingNumberApp', '0002_auto_20211114_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingnumber',
            name='parking_number',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)], verbose_name='Parking Number'),
        ),
        migrations.AlterUniqueTogether(
            name='parkingnumber',
            unique_together={('name',)},
        ),
    ]
