# Generated by Django 3.0.7 on 2021-11-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingNumberApp', '0003_auto_20211114_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingnumber',
            name='name',
            field=models.CharField(max_length=36, unique=True, verbose_name='Parking number'),
        ),
        migrations.AlterUniqueTogether(
            name='parkingnumber',
            unique_together={('name',), ('parking_number',)},
        ),
    ]
