# Generated by Django 3.0.7 on 2021-11-14 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingNumberApp', '0003_auto_20211114_1010'),
        ('ApartmentNumberApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentnumber',
            name='apartment_number',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)], verbose_name='Apartment Number'),
        ),
        migrations.AddField(
            model_name='apartmentnumber',
            name='parking_number',
            field=models.ManyToManyField(default=None, related_name='rn_apartment_number_parking_number', to='ParkingNumberApp.ParkingNumber', verbose_name='Parking Number'),
        ),
    ]
