# Generated by Django 3.0.7 on 2021-11-14 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentNumberApp', '0003_auto_20211114_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentnumber',
            name='apartment_number',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)], verbose_name='Apartment Number'),
        ),
    ]
