# Generated by Django 3.0.7 on 2021-11-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentNumberApp', '0004_auto_20211114_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentnumber',
            name='en_dis',
            field=models.BooleanField(default=True, verbose_name='Enable/Disable'),
        ),
    ]
