# Generated by Django 3.0.7 on 2021-11-14 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentOwnerApp', '0008_remove_apartmentowner_apartment_number'),
        ('ApartmentNumberApp', '0005_auto_20211114_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentNumberApartmentOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApartmentNumberApp.ApartmentNumber')),
                ('apartment_owner_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn_apartment_number_apartment_owner', to='ApartmentOwnerApp.ApartmentOwner', verbose_name='Apartment Owner')),
            ],
            options={
                'unique_together': {('apartment_number_id',)},
            },
        ),
    ]
