# Generated by Django 3.0.7 on 2021-11-14 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentOwnerApp', '0008_remove_apartmentowner_apartment_number'),
        ('ApartmentNumberApp', '0007_auto_20211114_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentnumberapartmentowner',
            name='apartment_owner_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn_apartments', to='ApartmentOwnerApp.ApartmentOwner', verbose_name='Apartment Owner'),
        ),
    ]
