# Generated by Django 3.0.7 on 2021-11-14 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentNumberApp', '0008_auto_20211114_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentnumber',
            name='parking_count',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)], verbose_name='Parking Count'),
        ),
    ]
