# Generated by Django 3.0.7 on 2021-11-14 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ApartmentNumberApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_dis', models.BooleanField(default=False, verbose_name='Enable/Disable')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=36, unique=True, verbose_name='Owner number')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Description')),
                ('apartment_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn_apartment_owner_apartment_number', to='ApartmentNumberApp.ApartmentNumber', verbose_name='Apartment Number')),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
    ]
