# Generated by Django 3.0.7 on 2021-11-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentNumberApp', '0001_initial'),
        ('ApartmentOwnerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentowner',
            name='apartment_number',
        ),
        migrations.AddField(
            model_name='apartmentowner',
            name='apartment_number',
            field=models.ManyToManyField(default=None, related_name='rn_apartment_owner_apartment_number', to='ApartmentNumberApp.ApartmentNumber', verbose_name='Apartment Number'),
        ),
    ]
