# Generated by Django 3.0.7 on 2021-11-14 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MotorcycleNumberApp', '0003_auto_20211114_1027'),
        ('CarNumberApp', '0003_auto_20211114_1027'),
        ('ApartmentOwnerApp', '0003_auto_20211114_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentowner',
            name='car_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn_apartment_owner_car_number', to='CarNumberApp.CarNumber', verbose_name='Car Number'),
        ),
        migrations.AddField(
            model_name='apartmentowner',
            name='motorcycle_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn_apartment_owner_motorcycle_number', to='MotorcycleNumberApp.MotorcycleNumber', verbose_name='Motorcycle Number'),
        ),
    ]
