# Generated by Django 3.0.7 on 2021-11-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotorcycleNumberApp', '0003_auto_20211114_1027'),
        ('CarNumberApp', '0003_auto_20211114_1027'),
        ('ApartmentOwnerApp', '0005_auto_20211114_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentowner',
            name='car_number',
        ),
        migrations.AddField(
            model_name='apartmentowner',
            name='car_number',
            field=models.ManyToManyField(default=None, related_name='rn_apartment_owner_car_number', to='CarNumberApp.CarNumber', verbose_name='Car Number'),
        ),
        migrations.RemoveField(
            model_name='apartmentowner',
            name='motorcycle_number',
        ),
        migrations.AddField(
            model_name='apartmentowner',
            name='motorcycle_number',
            field=models.ManyToManyField(default=None, related_name='rn_apartment_owner_motorcycle_number', to='MotorcycleNumberApp.MotorcycleNumber', verbose_name='Motorcycle Number'),
        ),
    ]
