# Generated by Django 3.0.7 on 2021-11-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentOwnerApp', '0006_auto_20211114_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentowner',
            name='car_number',
        ),
        migrations.RemoveField(
            model_name='apartmentowner',
            name='motorcycle_number',
        ),
    ]
