# Generated by Django 3.0.7 on 2021-11-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentOwnerApp', '0007_auto_20211114_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentowner',
            name='apartment_number',
        ),
    ]
