# Generated by Django 3.0.7 on 2022-04-06 05:42

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ApartmentNumberApp', '0010_auto_20211114_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=999, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Description')),
            ],
            options={
                'unique_together': {('category_name',)},
            },
        ),
        migrations.CreateModel(
            name='LeveledTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Description')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('apartment_number', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApartmentNumberApp.ApartmentNumber', verbose_name='Setup name')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='TreeApp.LeveledTree')),
            ],
            options={
                'unique_together': {('name',), ('apartment_number',)},
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=999, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Description')),
                ('variable_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TreeApp.Categories')),
            ],
            options={
                'ordering': ['variable_name'],
                'unique_together': {('variable_name',)},
            },
        ),
        migrations.CreateModel(
            name='ParametersTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_value', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Description')),
                ('fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parameters_leveled_tree', to='TreeApp.LeveledTree')),
                ('variable_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TreeApp.Parameters')),
            ],
            options={
                'unique_together': {('fk', 'variable_name')},
            },
        ),
    ]
